### ISSUE TITLE
monetize it!

### ISSUE THREAD

**Issue by torrlane** [tailuge/chess-o-tron#10]
https://github.com/begriffs/lucre

**Comment by tailuge** [comment]
if you could sed what I have sed'ed with your grep

cat git/chess-o-tron/html/js/endgames.js | grep fen | sed 's/[^pP]*//g' | sed 's/./#/g' | sort | uniq -c
    167 #
    108 ##
    142 ###
    171 ####
    153 #####
    248 ######
    144 #######
    230 ########
    133 #########
    257 ##########
    103 ###########
    215 ############
     38 #############
     77 ##############
      1 ################
