### ISSUE TITLE
Lichess API changes?

### ISSUE THREAD

**Issue by vitogit** [tailuge/chess-o-tron#11]
Do you know if the API changed? 
This is not working https://tailuge.github.io/chess-o-tron/public/openings/openingtree.html?player=tailuge&filter=&pages=1&colour=white&trim=true

I´m receiving a 404 when it tries to do ```https://en.lichess.org/api/user/tailuge/games?nb=100&with_analysis=1&with_moves=1&with_opening=1&page=1&_=1526573222082 404 (Not Found)```

**Comment by tailuge** [comment]
yes the API has changed, I hope to push a fix this weekend.

**Comment by tailuge** [comment]
Switched to new API

https://tailuge.github.io/chess-o-tron/public/openings/openingtree.html?player=TheFinnisher&filter=&pages=20&colour=white&trim=true
