### ISSUE TITLE
search-o-tron new version?

### ISSUE THREAD

**Issue by vitogit** [tailuge/chess-o-tron#12]
Hi I found this search-o-tron in the lichess forum https://jsfiddle.net/tailuge/7xpjkp7p/show/ but is not working. Do you have a new version?
It's look really interesting.

**Comment by tailuge** [comment]
I somehow forgot about that one - no plans to update yet, but maybe one of the others is of interest to you at https://tailuge.github.io/chess-o-tron/

**Comment by vitogit** [comment]
Yes, I know them all. Excellent stuff. 
I recommended some of your projects here https://lichess.org/forum/general-chess-discussion/list-of-free-and-open-source-chess-applications

I also like to do chess software http://vitomd.com/blog/projects/
I will try to update your fiddle when I have some time.
thanks.

**Comment by tailuge** [comment]
I have looked at some of those before, very nice - I want the blunder one to work but it is not loading, maybe I have too many games? Since you do lots of dev work I would definitely recommend trying out gitpod e.g. http://gitpod.io#https://github.com/vitogit/chess-winning-or-blunder  (you can log in with your github account)  edit and build in your browser

**Comment by vitogit** [comment]
I just tried the chess-winning-or-blunder  with your username and it worked, but it took a long time, like 3 minutes.  I have to work on that performance.
Thanks for the gitpod recommendation, i will take a look

**Comment by vitogit** [comment]
I fixed the search-o-tron https://jsfiddle.net/vitomd/kj8q1zay/45/

**Comment by tailuge** [comment]
oh very nice - feel free to link it from your site and look after it. I'm still playing lots of chess but coding some billiards for a change https://github.com/tailuge/billiards

**Comment by vitogit** [comment]
excellent tailuge and thanks. I will close this issue.
